### ISSUE TITLE
Error parsing Jupyter version

### ISSUE THREAD

**Issue by uvlad7** [hpi-swa/ipolyglot#29]
in setJupyterInfoAsync you parse version just executing "jupyter --version" and call
`context.frontend.version = stdout.toString().trim();
        context.frontend.majorVersion = parseInt(
            context.frontend.version.split(".")[0]
        );`
But output like that cause error
$ jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.6.0
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.2.3
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

**Comment by scfcode** [comment]
Also seen  while attempting a 'docker build --tag=ipolyglot .'

My Dockerfile was:

FROM oracle/graalvm-ce:19.3.0

RUN gu install python ruby R
# RUN /opt/graalvm-ce-19.3.0/jre/languages/ruby/lib/truffle/post_install_hook.sh
RUN /opt/graalvm-ce-java8-19.3.0/jre/languages/ruby/lib/truffle/post_install_hook.sh
RUN yum install -y python36 python36-devel python36-pip git
RUN easy_install-3.6 pip
RUN pip3 install -U pip
RUN pip3 install jupyter_core==4.6.1 jupyter
RUN pip3 install --upgrade jupyter_client

WORKDIR /code
COPY . .
RUN git clean -ffxd
RUN npm install . --unsafe-perm --nodedir="/opt/graalvm-ce-java8-19.3.0/jre/languages/js" --build-from-source
RUN git clone https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
RUN pip3 install -e jupyter_contrib_nbextensions
RUN cp -r varInspector jupyter_contrib_nbextensions/src/jupyter_contrib_nbextensions/nbextensions/
RUN jupyter contrib nbextensions install --user
RUN jupyter nbextension enable varInspector/main

WORKDIR /playground
EXPOSE 8888
CMD jupyter notebook --port=8888 --ip=0.0.0.0 --NotebookApp.token='' --allow-root --no-browser

---

Note I was attempting to get this going ... and battling other issues with the docker build, hence the edits above from the regular

**Comment by fniephaus** [comment]
It looks like this has been fixed upstream via https://github.com/n-riesco/ijavascript/commit/7ee18d2ca7144ff623f4f581b305c29989979f3a. I will cherry-pick the fix.

**Comment by fniephaus** [comment]
Fixed via https://github.com/hpi-swa/ipolyglot/commit/c4c4d426cf25dc89f6066d78fef3ef394afc82f5
