### ISSUE TITLE
Can not connect to ipolyglot kernel

### ISSUE THREAD

**Issue by Comee** [hpi-swa/ipolyglot#33]
The kernel was installed according to the installation tutorial, but the attempt to run failed

![image](https://user-images.githubusercontent.com/5416227/115952194-352e7500-a517-11eb-853f-66362c685e33.png)

**Comment by Comee** [comment]
rebuild zeromq then it worked

**Comment by fniephaus** [comment]
Excellent, thanks for the update and glad it's working now!
